[package]
name = "linkg16"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec = "0.3"
ark-ff = "0.3"
ark-serialize = { version = "0.3", features = [ "derive" ] }
ark-std = "0.3"
merlin = "3"

[dev-dependencies]
ark-bls12-381 = "0.3"
